# Generated by Django 6.0.3 on 2026-03-31 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100)),
                ('jd_text', models.TextField()),
                ('generation_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='quiz.job')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_prompt', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.joblevel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('easy_count', models.IntegerField(default=5)),
                ('medium_count', models.IntegerField(default=10)),
                ('hard_count', models.IntegerField(default=5)),
                ('secondary_exam_count', models.IntegerField(default=5)),
                ('is_finalized', models.BooleanField(default=False)),
                ('total_questions_limit', models.IntegerField(default=25)),
                ('is_adaptive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_job_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_quizzes', to='quiz.joblevel')),
                ('secondary_job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_quizzes', to='quiz.joblevel')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('magic_link_token', models.CharField(max_length=255, unique=True)),
                ('test_duration_mins', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Not_Started', 'Not Started'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], default='Not_Started', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='quiz.candidate')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_difficulty', models.CharField(default='Easy', max_length=10)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('consecutive_wrong', models.IntegerField(default=0)),
                ('total_q_answered', models.IntegerField(default=0)),
                ('running_score', models.IntegerField(default=0)),
                ('easy_pool', models.IntegerField(default=5)),
                ('medium_pool', models.IntegerField(default=10)),
                ('hard_pool', models.IntegerField(default=7)),
                ('total_easy_served', models.IntegerField(default=0)),
                ('is_gate_passed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_promotions', models.IntegerField(default=0, help_text='Number of times promoted to higher difficulty')),
                ('total_demotions', models.IntegerField(default=0, help_text='Number of times demoted to lower difficulty')),
                ('total_buffer_used', models.IntegerField(default=0, help_text='Total number of buffer questions used')),
                ('buffer_penalty_total', models.IntegerField(default=0, help_text='Total points lost from using buffer questions')),
                ('stepdown_penalty_total', models.IntegerField(default=0, help_text='Total points lost from demotions')),
                ('highest_difficulty_reached', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Secondary', 'Secondary')], default='Easy', help_text='Highest difficulty level reached during test', max_length=20)),
                ('current_question_started_at', models.DateTimeField(blank=True, help_text='When the current question was loaded', null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='quiz.assessment')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question')),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('buffer', 'Buffer')], max_length=10)),
                ('pool', models.CharField(choices=[('primary', 'Primary Pool'), ('secondary', 'Secondary Pool')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_entries', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['pool', 'difficulty', 'role', 'order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typed_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty_at_time', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Secondary', 'Secondary')], help_text='What difficulty level was active when this question was answered', max_length=20, null=True)),
                ('was_buffer_question', models.BooleanField(default=False, help_text='Was this question from the buffer pool?')),
                ('marks_awarded', models.IntegerField(default=0, help_text='Net marks for this question (can be negative due to penalties)')),
                ('action_taken', models.CharField(blank=True, choices=[('promote', 'Promoted'), ('demote', 'Demoted'), ('stay', 'Stayed')], help_text='What happened after this answer', max_length=20, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer this question', null=True)),
                ('score_before', models.IntegerField(default=0, help_text='Running score before answering this question')),
                ('score_after', models.IntegerField(default=0, help_text='Running score after answering this question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='quiz.questionoption')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.testsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['test_session', 'created_at'], name='quiz_respon_test_se_2864a0_idx')],
            },
        ),
    ]
