# Generated by Django 6.0.3 on 2026-03-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='quiz_respon_test_se_2864a0_idx',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='buffer_penalty_total',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='current_question_started_at',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='highest_difficulty_reached',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='stepdown_penalty_total',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='total_buffer_used',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='total_demotions',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='total_promotions',
        ),
        migrations.RemoveField(
            model_name='response',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='response',
            name='difficulty_at_time',
        ),
        migrations.RemoveField(
            model_name='response',
            name='marks_awarded',
        ),
        migrations.RemoveField(
            model_name='response',
            name='score_after',
        ),
        migrations.RemoveField(
            model_name='response',
            name='score_before',
        ),
        migrations.RemoveField(
            model_name='response',
            name='time_taken_seconds',
        ),
        migrations.RemoveField(
            model_name='response',
            name='was_buffer_question',
        ),
    ]
