# Generated by Django 6.0.3 on 2026-04-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
    ]
