# Generated by Django 6.0.3 on 2026-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='primary_job_level',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='secondary_exam_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='secondary_job_level',
        ),
        migrations.AddField(
            model_name='quiz',
            name='primary_job_levels',
            field=models.ManyToManyField(related_name='primary_quizzes', to='quiz.joblevel'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sec_easy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sec_hard_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sec_medium_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='secondary_job_levels',
            field=models.ManyToManyField(blank=True, related_name='secondary_quizzes', to='quiz.joblevel'),
        ),
    ]
