# Generated by Django 6.0.3 on 2026-04-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_primary_job_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='current_phase',
            field=models.CharField(choices=[('MAIN', 'Main Exam'), ('SECONDARY', 'Secondary Exam')], default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='main_exam_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='main_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='secondary_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='secondary_exam_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='main_q_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='main_running_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='sec_easy_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='sec_hard_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='sec_medium_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='secondary_q_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='secondary_running_score',
            field=models.IntegerField(default=0),
        ),
    ]
