# Generated by Django 6.0.3 on 2026-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_assessment_current_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='browser_lock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
