# Generated by Django 6.0.3 on 2026-04-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_assessment_browser_lock_assessment_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='browser_lock',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='termination_reason',
        ),
    ]
